### ISSUE TITLE
sos-guidelines pull request

### ISSUE THREAD

**Issue by robragsdale** [ioos/sos-guidelines-hugo#2]
@dpsnowden @abirger @Chris Duncombe Rae @carmelortiz
I've created a pull request to merge changes to the sos-guidelines repository. I assigned Derrick, but I think anyone could merge if they agree with the changes.  I could only assign people that were watching the repository.  Is there a way to assign people that are not watching?

**Comment by duncombe** [comment]
@robragsdale @dpsnowden 
Is this issue still open? I don't see any open pull requests so it should probably be closed?

**Comment by abirger** [comment]
@duncombe , do you see the pull request that I've opened about half an hour ago?..

**Comment by duncombe** [comment]
yes

On Fri, Oct 31, 2014 at 11:23 AM, abirger notifications@github.com wrote:

> @duncombe https://github.com/duncombe , do you see the pull request
> that I've opened about half an hour ago?..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ioos/sos-guidelines/issues/2#issuecomment-61276697.

## 

## 

## 

# 

Dr. Christopher M. Duncombe Rae       c deirdre.byrne@noaa.gov
hristopher.duncombe.rae@noaa.gov
Oceanographer / Data Scientist
IOOS/NOAA, Suite 1225, 1100 Wayne Avenue, Silver Spring, MD 20910, USA
Tel: +1-301-427-2450     Fax:  +1-301-427-2073

**Comment by duncombe** [comment]
@robragsdale: is this issue still open? (I think it has been dealt with! I don't see any outstanding pull requests.)

**Comment by robragsdale** [comment]
@duncombe This issue has been dealt with.
